<?php

/**
 * Implements hook_ctools_plugin_api().
 */
function mog_services_ctools_plugin_api($module, $api) {
  if ($module == 'services' && $api == 'services') {
    return array('version' => 3);
  }
}

/**
 *  Implements hook_default_services_endpoint().
 */
function mog_services_default_services_endpoint() {
  $export = array();

 // Export code start.
$endpoint->disabled = FALSE; /* Edit this to true to make a default endpoint disabled initially */
$endpoint->api_version = 3;
$endpoint->name = 'rest_endpoint';
$endpoint->server = 'rest_server';
$endpoint->path = 'rest';
$endpoint->authentication = array();
$endpoint->server_settings = array(
  'formatters' => array(
    'json' => TRUE,
    'bencode' => FALSE,
    'jsonp' => FALSE,
    'php' => FALSE,
    'rss' => FALSE,
    'xml' => FALSE,
  ),
  'parsers' => array(
    'application/json' => TRUE,
    'multipart/form-data' => TRUE,
    'application/vnd.php.serialized' => FALSE,
    'application/x-www-form-urlencoded' => FALSE,
    'application/xml' => FALSE,
    'text/xml' => FALSE,
  ),
);
$endpoint->resources = array(
  'node' => array(
    'operations' => array(
      'retrieve' => array(
        'enabled' => '1',
      ),
      'index' => array(
        'enabled' => '1',
      ),
    ),
  ),
);
$endpoint->debug = 0;

// Export code end.

// Store in export array under endpoint name key.
  $export['rest_endpoint'] = $endpoint;

  return $export;
}
